### ISSUE TITLE
Headers transparent

### ISSUE THREAD

**Issue by JadeD91** [Emrie-Candera/Bubble-Space-Theme#14]
Hello, thank's for your theme, I love it!
I have a problem with the Header, when insert a link the text becomes transparent.
Sorry for my English, I hope you can understand:
- Header normal is pink
- Header inside [[ ]] is transparent

it's a trouble

**Comment by carakitsune** [comment]
Same here, I absolutely love the theme! I'm even considering moving the links below the header, so that I can continue using it 🚀

**Comment by chadcatchyou** [comment]
same here. it really bother me because this theme is so good. i don't want to give it up by this little bug
![截圖 2022-04-24 下午12 49 23](https://user-images.githubusercontent.com/104290529/164957167-fc56944e-125e-416c-a878-9a917410c86f.png)

**Comment by sebastianhuus** [comment]
Hopping on the train here. Internal links in all header types show up as transparent, but hyperlinks work fine with all header types.

**Comment by Emrie-Candera** [comment]
Hello!

This has now been solved in the quick fix update [Bubble Space v1.6](https://github.com/Emrie-Candera/Bubble-Space-Theme/releases/tag/v1.6) 💜 

@JadeD91 @MagBec @carakitsune @chadcatchyou @sebastianhuus
