### ISSUE TITLE
No headers shown in embedded note

### ISSUE THREAD

**Issue by icegrim** [Emrie-Candera/Bubble-Space-Theme#16]
Hi, i want to report an issue. When i embed some note in another note, headers will not show. Can u look at this?

**Comment by Emrie-Candera** [comment]
Hello!

This has now been solved in the quick fix update [Bubble Space v1.6](https://github.com/Emrie-Candera/Bubble-Space-Theme/releases/tag/v1.6) 💜 

@icegrim
