### ISSUE TITLE
Nav image placement

### ISSUE THREAD

**Issue by nothingislost** [Emrie-Candera/Bubble-Space-Theme#2]
Hi Emrie, great theme! One bit of feedback would be that, as much as I like the tooting planet, maybe it should only live in the left nav bar? Check out what it looks like with the left+right bar as well as backlinks in document:

![image](https://user-images.githubusercontent.com/89109712/141178566-5e4350a9-c61d-4b14-998f-c4905703f950.png)

**Comment by Emrie-Candera** [comment]
Hello!

Thanks for the feedback and sorry for the late reply! Just figured out how to do this and it does look better that way 😅 
It will be included in tomorrow's release ❤️
