### ISSUE TITLE
Internal links in headers are invisible

### ISSUE THREAD

**Issue by alexture** [Emrie-Candera/Bubble-Space-Theme#20]
Hi! I absolutely love this theme, thanks so much for everything!

One issue that I have is that I can't put internal links inside headers :
![image](https://user-images.githubusercontent.com/8208894/174733473-e91a621b-3b2c-42db-a4de-28b093995c57.png)
![image](https://user-images.githubusercontent.com/8208894/174733494-d814d38f-d6b8-4870-8c3c-eb2877cf79cb.png)

I believe the links in the headers have the same colour as the background of the page, instead of having the normal link colours.

**Comment by Emrie-Candera** [comment]
Hello! Have you updated to the latest version of Bubble Space? I recently released a fix for this which works fine in the Sandbox vault

**Comment by alexture** [comment]
You're my hero!! I always remember to update plugins and always forget about themes!! Thank you so so much!
