### ISSUE TITLE
Checkboxes in live preview show default style

### ISSUE THREAD

**Issue by geoespi** [Emrie-Candera/Bubble-Space-Theme#5]
On PC in live preview mode, checkboxes are shown as the default obsidian styling, as shown on this screenshot.

![imagen](https://user-images.githubusercontent.com/49828522/148216624-dcafa046-ce94-4e91-a9ad-ce5afddeb515.png)

**Comment by Emrie-Candera** [comment]
Hi! Thanks for bringing this up. Are you perhaps using an insider version?

**Comment by geoespi** [comment]
No, I am using version 0.13.14. I can also confirm you that this happens no matter the preset used, or if its the light or dark themes.

Thanks for your work!

**Comment by geoespi** [comment]
Sorry, but it seems the issue was on my end. Did a full reinstall of the theme and now it works correctly.

Keep up the great work!
