### ISSUE TITLE
hr::after absolute positioning breaks hr in scrolling elements

### ISSUE THREAD

**Issue by geoespi** [Emrie-Candera/Bubble-Space-Theme#6]
Hello!

I have noticed that in some plugins which make use of hr elements in scrollable panes, small icon in the middle of the element stays in the same place when scrolling.

This is an example:
![imagen](https://user-images.githubusercontent.com/49828522/148515886-8343267d-2034-4a4b-9e69-4a99c84b4e30.png)
Here you can see that when it loads the stars look okay.
![imagen](https://user-images.githubusercontent.com/49828522/148516021-c0bffb36-8cb1-469b-aa39-6a51c03d59be.png)
here though you can see that the stars stay in the same place while the rest of the pane scrolls.

I've fixed it by making hr elements render overflow and hr::after show it as relative position. I also added a rule to not show the icons when it is on a resize bar on a leaf.

Will link a pull request shortly.

Thx!

**Comment by Emrie-Candera** [comment]
Thanks for opening this up and for the fix! Wasn't able to notice this because I don't use that pane so I'm thankful for the catch. Just merged the PR and it's fine now. Thanks again and have a nice day ❤️
